### ISSUE TITLE
Fix paths when saving after closing, opening & saving again

### ISSUE THREAD

**Issue by csaftoiu** [LogicalInnovation/sloth#4]
To reproduce:

• in bg-data repo
• start: `sloth --config config.py`
• add `live_boards3/live_boards3/live_boards3-test/0001/frame920.png`
• save to `live_boards3/foobar.json`
• close sloth. Path is *correct*  right now.
• open sloth: `sloth --config config.py`
• open `live_boards3/foobar.json`
• save
• close sloth
• Path is now *incorrect*.

**Comment by vc-souza** [comment]
Hey @csaftoiu the issue was:
- The paths saved in the config file were relative to the config file;
- But when we tried to save these paths again, the save function would handle these paths as relative to the current directory, what didn't work;

So that I did was add a new function during load time that takes the annotation list, and recreate the full path using the config file directory and the paths relative to it, for each annotation. Then when we try to save those again, the result makes sense again.

**Comment by vc-souza** [comment]
Here's the PR for the issue: #5.

**Comment by csaftoiu** [comment]
Makes sense! If we needed a conversion when saving, guess we need one when loading too.
